In [1]:
from selenium.webdriver import Edge
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver import ActionChains
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support import expected_conditions
from selenium.common.exceptions import NoSuchElementException
from selenium.common import exceptions  
from openpyxl import load_workbook
import pandas as pd 
import numpy as np

In [ ]:
"""
CLASS_NAME
CSS_SELECTOR
ID
LINK_TEXT
NAME
PARTIAL_LINK_TEXT
TAG_NAME
XPATH
"""

In [2]:
url='https://www.coursera.org/'
driver_path= 'msedgedriver'

browser= Edge(executable_path= driver_path)
browser.get(url)

In [3]:
element_searsh_field = browser.find_element(By.XPATH, '//input[starts-with(@class,"react-autosuggest")]')

element_searsh_field.clear()
element_searsh_field.send_keys('Data Science')
element_searsh_field.send_keys(Keys.ENTER)

In [6]:
Xpath='//*[@id="cds-react-aria-46"]'

In [42]:
Names = []
Stars = []
Reviews = []
Levels = []
Reviews = []
Skills = []
common=['University of Colorado Boulder', 'IBM','','Credit Eligible','CertNexus',
       'University of Michigan','University of Illinois','Illinois Institute of Technology'
       ,'Ball State University','University of Leeds','IIT Roorkee','University of Illinois at Urbana-Champaign']

In [43]:
for i in range(11):
    names = browser.find_elements(By.XPATH,'//h3[starts-with(@class,"cds-33 cds-CommonCard-title css-1wot210 cds-35")]')
    stars = browser.find_elements(By.XPATH,'//p[starts-with(@class,"cds-33 css-zl0kzj cds-35")]')
    levels = browser.find_elements(By.XPATH,'//p[starts-with(@class,"cds-33 css-14d8ngk")]')
    reviews = browser.find_elements(By.XPATH,'//p[starts-with(@class,"cds-33 css-14d8ngk cds-35")]')

    for i in range(len(names)):
        name = names[i].text
        if name == '':
            pass
        else:
            Names.append(name)

    for i in range(len(stars)):
        star = stars[i].text
        if star is None:
            Stars.append('null')
        else:    
            Stars.append(star)

    for i in range(len(levels)):
        level = levels[i].text
        if 'Skills' in level or 'reviews' in level or level in common:
            pass 
        else:
            Levels.append(level)     

    for i in range(len(levels)):
        level = levels[i].text
        if 'Skills' in level:
            Skills.append(level) 
        else:
            pass

    for i in range(len(reviews)):
        review = reviews[i].text
        if 'reviews' in review:
            Reviews.append(review)
        else:
            pass


    Pages = browser.find_element(By.XPATH,Xpath).click()

print(len(Names), "\n", len(Stars),'\n',len(Levels),len(Reviews), len(Skills))

132
 126
 132 126 131

In [44]:
missed = ['58',77,124,125,128,129]

for i in range(len(missed)):
    pos = int(missed[i])
    Stars.insert(pos, 'unknown')
    Reviews.insert(pos, 'unknown')
    if pos == 125:
        Skills.insert(pos, 'unknown')
    else:
        pass
    
    
print(len(Names), "\n", len(Stars),'\n',len(Levels),len(Reviews), len(Skills))

132
 132
 132 132 132

In [45]:
print(Names[125], Stars[125], Levels[125], Reviews[125], Skills[125])

Capstone: Data Science Problem in Linear Algebra Framework unknown Mixed · Course · 1-4 Weeks unknown unknown

In [55]:
Level = []
Type = []
Period = []

for i in range(len(Levels)):
    txt = []
    txt = Levels[i].split("·", 2)
    Level.append(txt[0])
    Type.append(txt[1])
    Period.append(txt[2])
    
print(Level[100],Type[100],Period[100])

Advanced   Course   1-4 Weeks

In [57]:
Data = pd.DataFrame()

Data['Name'] = Names
Data['Stars'] = Stars
Data['Reviews'] = Reviews
Data['Level'] = Level
Data['Type'] = Type
Data['Period'] = Period
Data['Skills'] = Skills


Data.to_excel('F:\\New folder\\Data Science.xlsx')
Data

,Name,Stars,Reviews,Level,Type,Period,Skills
0,IBM Data Science,4.6,(110.1k reviews),Beginner,Professional Certificate,3-6 Months,"Skills you'll gain: Python Programming, Data S..."
1,Google Data Analytics,4.8,(112.3k reviews),Beginner,Professional Certificate,3-6 Months,"Skills you'll gain: Data Analysis, Data Scienc..."
2,Introduction to Data Science,4.6,(79.6k reviews),Beginner,Specialization,3-6 Months,"Skills you'll gain: Data Science, Data Structu..."
3,Applied Data Science with Python,4.5,(33.1k reviews),Intermediate,Specialization,3-6 Months,"Skills you'll gain: Python Programming, Machin..."
4,Data Science,4.5,(50k reviews),Beginner,Specialization,3-6 Months,"Skills you'll gain: R Programming, Data Analys..."
...,...,...,...,...,...,...,...
127,Big Data Science with the BD2K-LINCS Data Coor...,4.8,(23 reviews),Intermediate,Course,3-6 Months,"Skills you'll gain: Data Management, Big Data"
128,Data science perspectives on pandemic management,unknown,unknown,Beginner,Course,1-3 Months,"Skills you'll gain: Data Science, Finance"
129,Python per la Data Science,unknown,unknown,Intermediate,Course,1-3 Months,"Skills you'll gain: Computer Programming, Pyth..."
130,Data Science at Scale - Capstone Project,4.1,(22 reviews),Mixed,Course,1-3 Months,"Skills you'll gain: Business Psychology, Commu..."
131,Data Science at Scale,4.2,(901 reviews),Intermediate,Specialization,3-6 Months,"Skills you'll gain: Data Management, Machine L..."